### ISSUE TITLE
Team Lead Task - Monitor Dev Environment Team Performance

### ISSUE THREAD

**Issue by NatiPerez459** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#112]
## Objective:
• Conduct meetings with the Dev Environment team, review completed assignments and overlook members activity throughout the Milestone maintaining documentation of accomplished activities guiding the database team towards success.

## Requirements:
• Establish weekly communications with the Dev Environment team to establish sprint goals, discuss progress and ideas for future assignments.
• Review completed assignments from team members to ensure they follow established requirements and guidelines.
• Review created code and ensured it complies with the requirements and passes test cases with the expected output.
• Maintain documentation of progress and established individual goals for the Milestone.

## Completion Criteria:
• Created record of meeting recordings, and minutes of important details discussed in meetings.
• All completed assignments have been reviewed and tagged with Lead Reviewed labels.
• Completed documentation of progress completed by individual team members and comparison of accomplishments with established team goals.

## Time Constraint:
• End of Milestone 2: October 25, 2024

## Scoring:
• Urgency: ?
• Difficulty: ?

**Comment by ActuallySeb** [comment]
Dev Env Team

What has been done during Milestone 2?
•	Issue #55 - Environment variables and dependency setup - Introduce the usage of environmental variables into the repository, install tools that allow access and usage to environment variables, and document the standard for future environment variables and their usage. Document local dependency installation procedure and remove current dependencies installed in the repository.
•	Issue #64 - Research Pass and secrets.js - Learn more about Pass, the standard UNIX password manager, to securely manage and use secrets in the project.
•	Issue #149 - [Lecture Topic Task] Documentation: Revamp Section 1 - Incorporating newer topics into the Informative Part - Incorporate the concept and usage of topics learned in class already present in the Milestone 2 Document such as domain engineering, requirements engineering, among others in section 1, "Informative Part".
•	Issue #163 - Documentation: Revise 2.2.4 Interface Requirements - Review and edit section 2.2.4 titled "Interface Requirements" of the Milestone 2 documentation to apply the feedback given by the professor to break-down current high level format into specific requirements.
•	Issue #168 - Documentation: Revise 3.1 Concept Analysis - Review and edit section 3.1 titled "Concept Analysis" of the Milestone 2 documentation to apply the feedback given by the professor to clarify the process of identifying and naming common themes from user stories.
•	Issue #85 - Research Containerization & Orchestration - Learn how to use containerization to streamline and simplify the Development Environment with tools like Docker.
•	Issue #170 - Container Implementation - Setup Dockerfile for front end to eliminate external factors from creating issues in the development process born from using mismatched versions of software. before adding additional container for the backend.
Could not be completed:
•	Issue #160 - Pass implementation – Could not implement Pass to the source code to secure the data contained in the .env file because it requires to be implemented alongside Docker.
•	Issue #70 - Email Confirmation - The database isn't fully implemented so we can't link the users emails, and usernames. Since we can't implement these features, testing will not be possible.

**Comment by ActuallySeb** [comment]
[Dev Env Team - M2.docx](https://github.com/user-attachments/files/17528427/Dev.Env.Team.-.M2.docx)

**Comment by ActuallySeb** [comment]
[Dev Env Team - M2.docx](https://github.com/user-attachments/files/17528482/Dev.Env.Team.-.M2.docx)
