### ISSUE TITLE
Database Design: Setup Database Hosting for Project

### ISSUE THREAD

**Issue by franRov** [uprm-inso4101-2024-2025-s1/semester-project-mercado-colegial-online#34]
•Objective: Set up a database hosting service for the project to store and manage data for collaborative features. This will allows members to access and update information in real-time

Requirements:
- Choose a suitable database hosting provider 
- Set up a database to handle at least 20 active collaborators
- Ensure the database supports key features, such as real-time updates, backups, and security (Oh, and have it be free for now)
- Integrate the database with the project's backend

Completion Criteria:
- A functional, hosted database is accessible by the backend
- A large group of members can interact with the database without performance issues.
- Basic database features i.e. user authentication are implemented

Time Constraint: Monday September 9th

Urgency: 6
Difficulty: 6

**Comment by CovasJJ** [comment]
After doing some research on the free tier of MongoDB Atlas I believe it does fit many of our needs but it has some limitations that should be considered. The free tier supports real-time operations. One problem with the free tier is that automated backups are not available, which poses a risk for data recovery. But, there is an alternate way to create backups through "mongodump" (export-import of data system, info linked at the bottom). The free tier also includes role-based access control, allowing for the creation of user roles and permissions, which is useful for secure collaboration. This tier will allow 20 active collaborators. It has a storage limit of 512 MB, which should be enough, monitoring usage is essential. In conclusion, while the free tier can meet our foundational requirements, we have to be careful moving forward with this host since there are no automated backups. 

Mongodump: https://www.mongodb.com/docs/database-tools/mongodump/#mongodb-binary-bin.mongodump

**Comment by Christian2101** [comment]
After extensive research on Mongodb I found that Atlas is a great host provider to use. It has a free service that although limited provides many of our required needs, such as allow at least the needed 20 collaborators and support  real-time updates. A problem that I found on it is the backups not being available. A fix for this problem is using "Mongodump" for exporting data and "mongorestore" for importing data. 

Mongodump: https://www.mongodb.com/docs/database-tools/mongodump/

Mongorestore: https://www.mongodb.com/docs/database-tools/mongorestore/#mongodb-binary-bin.mongorestore

**Comment by franRov** [comment]
I team leader, confirm this as completed. We have succesfully managed to find and setup a database service provider that will host our data in the cloud. 

Next step in develoment, is to create user/password for every DB team member, allowing access and visibility for the future management of incoming data.
